/*
Hoarder API

Testing HighlightsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_HighlightsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test HighlightsAPIService HighlightsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.HighlightsAPI.HighlightsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HighlightsAPIService HighlightsHighlightIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var highlightId string

		resp, httpRes, err := apiClient.HighlightsAPI.HighlightsHighlightIdDelete(context.Background(), highlightId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HighlightsAPIService HighlightsHighlightIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var highlightId string

		resp, httpRes, err := apiClient.HighlightsAPI.HighlightsHighlightIdGet(context.Background(), highlightId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HighlightsAPIService HighlightsHighlightIdPatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var highlightId string

		resp, httpRes, err := apiClient.HighlightsAPI.HighlightsHighlightIdPatch(context.Background(), highlightId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HighlightsAPIService HighlightsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.HighlightsAPI.HighlightsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
