/*
Hoarder API

The API for the Hoarder app

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedHighlights type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedHighlights{}

// PaginatedHighlights struct for PaginatedHighlights
type PaginatedHighlights struct {
	Highlights []Highlight `json:"highlights"`
	NextCursor NullableString `json:"nextCursor"`
}

type _PaginatedHighlights PaginatedHighlights

// NewPaginatedHighlights instantiates a new PaginatedHighlights object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedHighlights(highlights []Highlight, nextCursor NullableString) *PaginatedHighlights {
	this := PaginatedHighlights{}
	this.Highlights = highlights
	this.NextCursor = nextCursor
	return &this
}

// NewPaginatedHighlightsWithDefaults instantiates a new PaginatedHighlights object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedHighlightsWithDefaults() *PaginatedHighlights {
	this := PaginatedHighlights{}
	return &this
}

// GetHighlights returns the Highlights field value
func (o *PaginatedHighlights) GetHighlights() []Highlight {
	if o == nil {
		var ret []Highlight
		return ret
	}

	return o.Highlights
}

// GetHighlightsOk returns a tuple with the Highlights field value
// and a boolean to check if the value has been set.
func (o *PaginatedHighlights) GetHighlightsOk() ([]Highlight, bool) {
	if o == nil {
		return nil, false
	}
	return o.Highlights, true
}

// SetHighlights sets field value
func (o *PaginatedHighlights) SetHighlights(v []Highlight) {
	o.Highlights = v
}

// GetNextCursor returns the NextCursor field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaginatedHighlights) GetNextCursor() string {
	if o == nil || o.NextCursor.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedHighlights) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// SetNextCursor sets field value
func (o *PaginatedHighlights) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

func (o PaginatedHighlights) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedHighlights) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["highlights"] = o.Highlights
	toSerialize["nextCursor"] = o.NextCursor.Get()
	return toSerialize, nil
}

func (o *PaginatedHighlights) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"highlights",
		"nextCursor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedHighlights := _PaginatedHighlights{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedHighlights)

	if err != nil {
		return err
	}

	*o = PaginatedHighlights(varPaginatedHighlights)

	return err
}

type NullablePaginatedHighlights struct {
	value *PaginatedHighlights
	isSet bool
}

func (v NullablePaginatedHighlights) Get() *PaginatedHighlights {
	return v.value
}

func (v *NullablePaginatedHighlights) Set(val *PaginatedHighlights) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedHighlights) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedHighlights) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedHighlights(val *PaginatedHighlights) *NullablePaginatedHighlights {
	return &NullablePaginatedHighlights{value: val, isSet: true}
}

func (v NullablePaginatedHighlights) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedHighlights) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


