/*
Hoarder API

The API for the Hoarder app

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BookmarksBookmarkIdAssetsPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BookmarksBookmarkIdAssetsPostRequest{}

// BookmarksBookmarkIdAssetsPostRequest struct for BookmarksBookmarkIdAssetsPostRequest
type BookmarksBookmarkIdAssetsPostRequest struct {
	Id string `json:"id"`
	AssetType string `json:"assetType"`
}

type _BookmarksBookmarkIdAssetsPostRequest BookmarksBookmarkIdAssetsPostRequest

// NewBookmarksBookmarkIdAssetsPostRequest instantiates a new BookmarksBookmarkIdAssetsPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookmarksBookmarkIdAssetsPostRequest(id string, assetType string) *BookmarksBookmarkIdAssetsPostRequest {
	this := BookmarksBookmarkIdAssetsPostRequest{}
	this.Id = id
	this.AssetType = assetType
	return &this
}

// NewBookmarksBookmarkIdAssetsPostRequestWithDefaults instantiates a new BookmarksBookmarkIdAssetsPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookmarksBookmarkIdAssetsPostRequestWithDefaults() *BookmarksBookmarkIdAssetsPostRequest {
	this := BookmarksBookmarkIdAssetsPostRequest{}
	return &this
}

// GetId returns the Id field value
func (o *BookmarksBookmarkIdAssetsPostRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BookmarksBookmarkIdAssetsPostRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BookmarksBookmarkIdAssetsPostRequest) SetId(v string) {
	o.Id = v
}

// GetAssetType returns the AssetType field value
func (o *BookmarksBookmarkIdAssetsPostRequest) GetAssetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetType
}

// GetAssetTypeOk returns a tuple with the AssetType field value
// and a boolean to check if the value has been set.
func (o *BookmarksBookmarkIdAssetsPostRequest) GetAssetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetType, true
}

// SetAssetType sets field value
func (o *BookmarksBookmarkIdAssetsPostRequest) SetAssetType(v string) {
	o.AssetType = v
}

func (o BookmarksBookmarkIdAssetsPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BookmarksBookmarkIdAssetsPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["assetType"] = o.AssetType
	return toSerialize, nil
}

func (o *BookmarksBookmarkIdAssetsPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"assetType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBookmarksBookmarkIdAssetsPostRequest := _BookmarksBookmarkIdAssetsPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBookmarksBookmarkIdAssetsPostRequest)

	if err != nil {
		return err
	}

	*o = BookmarksBookmarkIdAssetsPostRequest(varBookmarksBookmarkIdAssetsPostRequest)

	return err
}

type NullableBookmarksBookmarkIdAssetsPostRequest struct {
	value *BookmarksBookmarkIdAssetsPostRequest
	isSet bool
}

func (v NullableBookmarksBookmarkIdAssetsPostRequest) Get() *BookmarksBookmarkIdAssetsPostRequest {
	return v.value
}

func (v *NullableBookmarksBookmarkIdAssetsPostRequest) Set(val *BookmarksBookmarkIdAssetsPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBookmarksBookmarkIdAssetsPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBookmarksBookmarkIdAssetsPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookmarksBookmarkIdAssetsPostRequest(val *BookmarksBookmarkIdAssetsPostRequest) *NullableBookmarksBookmarkIdAssetsPostRequest {
	return &NullableBookmarksBookmarkIdAssetsPostRequest{value: val, isSet: true}
}

func (v NullableBookmarksBookmarkIdAssetsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookmarksBookmarkIdAssetsPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


