/*
Hoarder API

The API for the Hoarder app

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BookmarksBookmarkIdTagsPostRequestTagsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BookmarksBookmarkIdTagsPostRequestTagsInner{}

// BookmarksBookmarkIdTagsPostRequestTagsInner struct for BookmarksBookmarkIdTagsPostRequestTagsInner
type BookmarksBookmarkIdTagsPostRequestTagsInner struct {
	TagId   *string `json:"tagId,omitempty"`
	TagName *string `json:"tagName,omitempty"`
}

// NewBookmarksBookmarkIdTagsPostRequestTagsInner instantiates a new BookmarksBookmarkIdTagsPostRequestTagsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookmarksBookmarkIdTagsPostRequestTagsInner() *BookmarksBookmarkIdTagsPostRequestTagsInner {
	this := BookmarksBookmarkIdTagsPostRequestTagsInner{}
	return &this
}

// NewBookmarksBookmarkIdTagsPostRequestTagsInnerWithDefaults instantiates a new BookmarksBookmarkIdTagsPostRequestTagsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookmarksBookmarkIdTagsPostRequestTagsInnerWithDefaults() *BookmarksBookmarkIdTagsPostRequestTagsInner {
	this := BookmarksBookmarkIdTagsPostRequestTagsInner{}
	return &this
}

// GetTagId returns the TagId field value if set, zero value otherwise.
func (o *BookmarksBookmarkIdTagsPostRequestTagsInner) GetTagId() string {
	if o == nil || IsNil(o.TagId) {
		var ret string
		return ret
	}
	return *o.TagId
}

// GetTagIdOk returns a tuple with the TagId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookmarksBookmarkIdTagsPostRequestTagsInner) GetTagIdOk() (*string, bool) {
	if o == nil || IsNil(o.TagId) {
		return nil, false
	}
	return o.TagId, true
}

// HasTagId returns a boolean if a field has been set.
func (o *BookmarksBookmarkIdTagsPostRequestTagsInner) HasTagId() bool {
	if o != nil && !IsNil(o.TagId) {
		return true
	}

	return false
}

// SetTagId gets a reference to the given string and assigns it to the TagId field.
func (o *BookmarksBookmarkIdTagsPostRequestTagsInner) SetTagId(v string) {
	o.TagId = &v
}

// GetTagName returns the TagName field value if set, zero value otherwise.
func (o *BookmarksBookmarkIdTagsPostRequestTagsInner) GetTagName() string {
	if o == nil || IsNil(o.TagName) {
		var ret string
		return ret
	}
	return *o.TagName
}

// GetTagNameOk returns a tuple with the TagName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookmarksBookmarkIdTagsPostRequestTagsInner) GetTagNameOk() (*string, bool) {
	if o == nil || IsNil(o.TagName) {
		return nil, false
	}
	return o.TagName, true
}

// HasTagName returns a boolean if a field has been set.
func (o *BookmarksBookmarkIdTagsPostRequestTagsInner) HasTagName() bool {
	if o != nil && !IsNil(o.TagName) {
		return true
	}

	return false
}

// SetTagName gets a reference to the given string and assigns it to the TagName field.
func (o *BookmarksBookmarkIdTagsPostRequestTagsInner) SetTagName(v string) {
	o.TagName = &v
}

func (o BookmarksBookmarkIdTagsPostRequestTagsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BookmarksBookmarkIdTagsPostRequestTagsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TagId) {
		toSerialize["tagId"] = o.TagId
	}
	if !IsNil(o.TagName) {
		toSerialize["tagName"] = o.TagName
	}
	return toSerialize, nil
}

type NullableBookmarksBookmarkIdTagsPostRequestTagsInner struct {
	value *BookmarksBookmarkIdTagsPostRequestTagsInner
	isSet bool
}

func (v NullableBookmarksBookmarkIdTagsPostRequestTagsInner) Get() *BookmarksBookmarkIdTagsPostRequestTagsInner {
	return v.value
}

func (v *NullableBookmarksBookmarkIdTagsPostRequestTagsInner) Set(val *BookmarksBookmarkIdTagsPostRequestTagsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBookmarksBookmarkIdTagsPostRequestTagsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBookmarksBookmarkIdTagsPostRequestTagsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookmarksBookmarkIdTagsPostRequestTagsInner(val *BookmarksBookmarkIdTagsPostRequestTagsInner) *NullableBookmarksBookmarkIdTagsPostRequestTagsInner {
	return &NullableBookmarksBookmarkIdTagsPostRequestTagsInner{value: val, isSet: true}
}

func (v NullableBookmarksBookmarkIdTagsPostRequestTagsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookmarksBookmarkIdTagsPostRequestTagsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
