/*
Hoarder API

The API for the Hoarder app

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BookmarkContentOneOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BookmarkContentOneOf3{}

// BookmarkContentOneOf3 struct for BookmarkContentOneOf3
type BookmarkContentOneOf3 struct {
	Type string `json:"type"`
}

type _BookmarkContentOneOf3 BookmarkContentOneOf3

// NewBookmarkContentOneOf3 instantiates a new BookmarkContentOneOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookmarkContentOneOf3(type_ string) *BookmarkContentOneOf3 {
	this := BookmarkContentOneOf3{}
	this.Type = type_
	return &this
}

// NewBookmarkContentOneOf3WithDefaults instantiates a new BookmarkContentOneOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookmarkContentOneOf3WithDefaults() *BookmarkContentOneOf3 {
	this := BookmarkContentOneOf3{}
	return &this
}

// GetType returns the Type field value
func (o *BookmarkContentOneOf3) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BookmarkContentOneOf3) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BookmarkContentOneOf3) SetType(v string) {
	o.Type = v
}

func (o BookmarkContentOneOf3) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BookmarkContentOneOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *BookmarkContentOneOf3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBookmarkContentOneOf3 := _BookmarkContentOneOf3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBookmarkContentOneOf3)

	if err != nil {
		return err
	}

	*o = BookmarkContentOneOf3(varBookmarkContentOneOf3)

	return err
}

type NullableBookmarkContentOneOf3 struct {
	value *BookmarkContentOneOf3
	isSet bool
}

func (v NullableBookmarkContentOneOf3) Get() *BookmarkContentOneOf3 {
	return v.value
}

func (v *NullableBookmarkContentOneOf3) Set(val *BookmarkContentOneOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableBookmarkContentOneOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableBookmarkContentOneOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookmarkContentOneOf3(val *BookmarkContentOneOf3) *NullableBookmarkContentOneOf3 {
	return &NullableBookmarkContentOneOf3{value: val, isSet: true}
}

func (v NullableBookmarkContentOneOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookmarkContentOneOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
