/*
Hoarder API

The API for the Hoarder app

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TagsTagIdPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagsTagIdPatchRequest{}

// TagsTagIdPatchRequest struct for TagsTagIdPatchRequest
type TagsTagIdPatchRequest struct {
	Name *string `json:"name,omitempty"`
}

// NewTagsTagIdPatchRequest instantiates a new TagsTagIdPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagsTagIdPatchRequest() *TagsTagIdPatchRequest {
	this := TagsTagIdPatchRequest{}
	return &this
}

// NewTagsTagIdPatchRequestWithDefaults instantiates a new TagsTagIdPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagsTagIdPatchRequestWithDefaults() *TagsTagIdPatchRequest {
	this := TagsTagIdPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TagsTagIdPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagsTagIdPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TagsTagIdPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TagsTagIdPatchRequest) SetName(v string) {
	o.Name = &v
}

func (o TagsTagIdPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagsTagIdPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableTagsTagIdPatchRequest struct {
	value *TagsTagIdPatchRequest
	isSet bool
}

func (v NullableTagsTagIdPatchRequest) Get() *TagsTagIdPatchRequest {
	return v.value
}

func (v *NullableTagsTagIdPatchRequest) Set(val *TagsTagIdPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTagsTagIdPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTagsTagIdPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagsTagIdPatchRequest(val *TagsTagIdPatchRequest) *NullableTagsTagIdPatchRequest {
	return &NullableTagsTagIdPatchRequest{value: val, isSet: true}
}

func (v NullableTagsTagIdPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagsTagIdPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


