/*
Hoarder API

The API for the Hoarder app

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BookmarksBookmarkIdAssetsAssetIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BookmarksBookmarkIdAssetsAssetIdPutRequest{}

// BookmarksBookmarkIdAssetsAssetIdPutRequest struct for BookmarksBookmarkIdAssetsAssetIdPutRequest
type BookmarksBookmarkIdAssetsAssetIdPutRequest struct {
	AssetId string `json:"assetId"`
}

type _BookmarksBookmarkIdAssetsAssetIdPutRequest BookmarksBookmarkIdAssetsAssetIdPutRequest

// NewBookmarksBookmarkIdAssetsAssetIdPutRequest instantiates a new BookmarksBookmarkIdAssetsAssetIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookmarksBookmarkIdAssetsAssetIdPutRequest(assetId string) *BookmarksBookmarkIdAssetsAssetIdPutRequest {
	this := BookmarksBookmarkIdAssetsAssetIdPutRequest{}
	this.AssetId = assetId
	return &this
}

// NewBookmarksBookmarkIdAssetsAssetIdPutRequestWithDefaults instantiates a new BookmarksBookmarkIdAssetsAssetIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookmarksBookmarkIdAssetsAssetIdPutRequestWithDefaults() *BookmarksBookmarkIdAssetsAssetIdPutRequest {
	this := BookmarksBookmarkIdAssetsAssetIdPutRequest{}
	return &this
}

// GetAssetId returns the AssetId field value
func (o *BookmarksBookmarkIdAssetsAssetIdPutRequest) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *BookmarksBookmarkIdAssetsAssetIdPutRequest) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *BookmarksBookmarkIdAssetsAssetIdPutRequest) SetAssetId(v string) {
	o.AssetId = v
}

func (o BookmarksBookmarkIdAssetsAssetIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BookmarksBookmarkIdAssetsAssetIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["assetId"] = o.AssetId
	return toSerialize, nil
}

func (o *BookmarksBookmarkIdAssetsAssetIdPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"assetId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBookmarksBookmarkIdAssetsAssetIdPutRequest := _BookmarksBookmarkIdAssetsAssetIdPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBookmarksBookmarkIdAssetsAssetIdPutRequest)

	if err != nil {
		return err
	}

	*o = BookmarksBookmarkIdAssetsAssetIdPutRequest(varBookmarksBookmarkIdAssetsAssetIdPutRequest)

	return err
}

type NullableBookmarksBookmarkIdAssetsAssetIdPutRequest struct {
	value *BookmarksBookmarkIdAssetsAssetIdPutRequest
	isSet bool
}

func (v NullableBookmarksBookmarkIdAssetsAssetIdPutRequest) Get() *BookmarksBookmarkIdAssetsAssetIdPutRequest {
	return v.value
}

func (v *NullableBookmarksBookmarkIdAssetsAssetIdPutRequest) Set(val *BookmarksBookmarkIdAssetsAssetIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBookmarksBookmarkIdAssetsAssetIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBookmarksBookmarkIdAssetsAssetIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookmarksBookmarkIdAssetsAssetIdPutRequest(val *BookmarksBookmarkIdAssetsAssetIdPutRequest) *NullableBookmarksBookmarkIdAssetsAssetIdPutRequest {
	return &NullableBookmarksBookmarkIdAssetsAssetIdPutRequest{value: val, isSet: true}
}

func (v NullableBookmarksBookmarkIdAssetsAssetIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookmarksBookmarkIdAssetsAssetIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


