/*
Hoarder API

The API for the Hoarder app

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BookmarksBookmarkIdTagsPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BookmarksBookmarkIdTagsPostRequest{}

// BookmarksBookmarkIdTagsPostRequest struct for BookmarksBookmarkIdTagsPostRequest
type BookmarksBookmarkIdTagsPostRequest struct {
	Tags []BookmarksBookmarkIdTagsPostRequestTagsInner `json:"tags"`
}

type _BookmarksBookmarkIdTagsPostRequest BookmarksBookmarkIdTagsPostRequest

// NewBookmarksBookmarkIdTagsPostRequest instantiates a new BookmarksBookmarkIdTagsPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookmarksBookmarkIdTagsPostRequest(tags []BookmarksBookmarkIdTagsPostRequestTagsInner) *BookmarksBookmarkIdTagsPostRequest {
	this := BookmarksBookmarkIdTagsPostRequest{}
	this.Tags = tags
	return &this
}

// NewBookmarksBookmarkIdTagsPostRequestWithDefaults instantiates a new BookmarksBookmarkIdTagsPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookmarksBookmarkIdTagsPostRequestWithDefaults() *BookmarksBookmarkIdTagsPostRequest {
	this := BookmarksBookmarkIdTagsPostRequest{}
	return &this
}

// GetTags returns the Tags field value
func (o *BookmarksBookmarkIdTagsPostRequest) GetTags() []BookmarksBookmarkIdTagsPostRequestTagsInner {
	if o == nil {
		var ret []BookmarksBookmarkIdTagsPostRequestTagsInner
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *BookmarksBookmarkIdTagsPostRequest) GetTagsOk() ([]BookmarksBookmarkIdTagsPostRequestTagsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *BookmarksBookmarkIdTagsPostRequest) SetTags(v []BookmarksBookmarkIdTagsPostRequestTagsInner) {
	o.Tags = v
}

func (o BookmarksBookmarkIdTagsPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BookmarksBookmarkIdTagsPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tags"] = o.Tags
	return toSerialize, nil
}

func (o *BookmarksBookmarkIdTagsPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBookmarksBookmarkIdTagsPostRequest := _BookmarksBookmarkIdTagsPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBookmarksBookmarkIdTagsPostRequest)

	if err != nil {
		return err
	}

	*o = BookmarksBookmarkIdTagsPostRequest(varBookmarksBookmarkIdTagsPostRequest)

	return err
}

type NullableBookmarksBookmarkIdTagsPostRequest struct {
	value *BookmarksBookmarkIdTagsPostRequest
	isSet bool
}

func (v NullableBookmarksBookmarkIdTagsPostRequest) Get() *BookmarksBookmarkIdTagsPostRequest {
	return v.value
}

func (v *NullableBookmarksBookmarkIdTagsPostRequest) Set(val *BookmarksBookmarkIdTagsPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBookmarksBookmarkIdTagsPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBookmarksBookmarkIdTagsPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookmarksBookmarkIdTagsPostRequest(val *BookmarksBookmarkIdTagsPostRequest) *NullableBookmarksBookmarkIdTagsPostRequest {
	return &NullableBookmarksBookmarkIdTagsPostRequest{value: val, isSet: true}
}

func (v NullableBookmarksBookmarkIdTagsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookmarksBookmarkIdTagsPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
